# TCL File Generated by Component Editor 21.3
# Thu Sep 21 12:11:56 MSK 2023
# DO NOT MODIFY


# 
# send_cmd_pcie "send_cmd_pcie" v1.0
#  2023.09.21.12:11:56
# 
# 

# 
# request TCL package from ACDS 21.3
# 
package require -exact qsys 21.3


# 
# module send_cmd_pcie
# 
set_module_property DESCRIPTION ""
set_module_property NAME send_cmd_pcie
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME send_cmd_pcie
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_mm_slave
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_mm_slave.sv SYSTEM_VERILOG PATH modules/pci/avalon_mm_slave.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL avalon_mm_slave
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_mm_slave.sv SYSTEM_VERILOG PATH modules/pci/avalon_mm_slave.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""
set_interface_property clock IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock ""
set_interface_property reset synchronousEdges NONE
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""
set_interface_property reset IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port reset rst_n reset_n Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressGroup 0
set_interface_property avalon_slave addressUnits SYMBOLS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave bridgedAddressOffset ""
set_interface_property avalon_slave bridgesToMaster ""
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits SYMBOLS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 1
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave minimumResponseLatency 1
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitStates 0
set_interface_property avalon_slave readWaitTime 0
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave transparentBridge false
set_interface_property avalon_slave waitrequestAllowance 0
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""
set_interface_property avalon_slave IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port avalon_slave avalon_mm_read read Input 1
add_interface_port avalon_slave avalon_mm_write write Input 1
add_interface_port avalon_slave avalon_mm_addr address Input 16
add_interface_port avalon_slave avalon_mm_write_data writedata Input 32
add_interface_port avalon_slave avalon_mm_read_data readdata Output 32
add_interface_port avalon_slave avalon_mm_rd_valid readdatavalid Output 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point send_control
# 
add_interface send_control conduit end
set_interface_property send_control associatedClock clock
set_interface_property send_control associatedReset reset
set_interface_property send_control ENABLED true
set_interface_property send_control EXPORT_OF ""
set_interface_property send_control PORT_NAME_MAP ""
set_interface_property send_control CMSIS_SVD_VARIABLES ""
set_interface_property send_control SVD_ADDRESS_GROUP ""
set_interface_property send_control IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port send_control start_ram_addr start_ram_addr Output 6
add_interface_port send_control send_cmd signal Output 1
add_interface_port send_control send_ch_2_timer ch_2_timer Output 32


# 
# connection point ddr_status
# 
add_interface ddr_status conduit end
set_interface_property ddr_status associatedClock ""
set_interface_property ddr_status associatedReset ""
set_interface_property ddr_status ENABLED true
set_interface_property ddr_status EXPORT_OF ""
set_interface_property ddr_status PORT_NAME_MAP ""
set_interface_property ddr_status CMSIS_SVD_VARIABLES ""
set_interface_property ddr_status SVD_ADDRESS_GROUP ""
set_interface_property ddr_status IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port ddr_status ddr_local_cal_success local_cal_success Input 1
add_interface_port ddr_status ddr_local_cal_fail local_cal_fail Input 1


# 
# connection point ddr_setup_done
# 
add_interface ddr_setup_done conduit end
set_interface_property ddr_setup_done associatedClock ""
set_interface_property ddr_setup_done associatedReset ""
set_interface_property ddr_setup_done ENABLED true
set_interface_property ddr_setup_done EXPORT_OF ""
set_interface_property ddr_setup_done PORT_NAME_MAP ""
set_interface_property ddr_setup_done CMSIS_SVD_VARIABLES ""
set_interface_property ddr_setup_done SVD_ADDRESS_GROUP ""
set_interface_property ddr_setup_done IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port ddr_setup_done ddr_setup_done setup_done Input 1


# 
# connection point resets_information
# 
add_interface resets_information conduit end
set_interface_property resets_information associatedClock ""
set_interface_property resets_information associatedReset ""
set_interface_property resets_information ENABLED true
set_interface_property resets_information EXPORT_OF ""
set_interface_property resets_information PORT_NAME_MAP ""
set_interface_property resets_information CMSIS_SVD_VARIABLES ""
set_interface_property resets_information SVD_ADDRESS_GROUP ""
set_interface_property resets_information IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port resets_information system_main_reset main_reset Input 1
add_interface_port resets_information ddr_avalon_rst ddr_avalon_reset Input 1
add_interface_port resets_information board_reset board_reset Input 1


# 
# connection point ddr_setup_cmd
# 
add_interface ddr_setup_cmd conduit end
set_interface_property ddr_setup_cmd associatedClock ""
set_interface_property ddr_setup_cmd associatedReset ""
set_interface_property ddr_setup_cmd ENABLED true
set_interface_property ddr_setup_cmd EXPORT_OF ""
set_interface_property ddr_setup_cmd PORT_NAME_MAP ""
set_interface_property ddr_setup_cmd CMSIS_SVD_VARIABLES ""
set_interface_property ddr_setup_cmd SVD_ADDRESS_GROUP ""
set_interface_property ddr_setup_cmd IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port ddr_setup_cmd ddr_setup_cmd ddr_setup_cmd Output 1

