// system_design_altera_mm_interconnect_1920_rvh6iyy.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 21.3 170

`timescale 1 ps / 1 ps
module system_design_altera_mm_interconnect_1920_rvh6iyy (
		input  wire [9:0]  receive_packet_2_avalon_master_address,             //               receive_packet_2_avalon_master.address
		output wire        receive_packet_2_avalon_master_waitrequest,         //                                             .waitrequest
		input  wire [3:0]  receive_packet_2_avalon_master_byteenable,          //                                             .byteenable
		input  wire        receive_packet_2_avalon_master_chipselect,          //                                             .chipselect
		output wire [31:0] receive_packet_2_avalon_master_readdata,            //                                             .readdata
		input  wire        receive_packet_2_avalon_master_write,               //                                             .write
		input  wire [31:0] receive_packet_2_avalon_master_writedata,           //                                             .writedata
		output wire [9:0]  mem_4_s2_address,                                   //                                     mem_4_s2.address
		output wire        mem_4_s2_write,                                     //                                             .write
		input  wire [31:0] mem_4_s2_readdata,                                  //                                             .readdata
		output wire [31:0] mem_4_s2_writedata,                                 //                                             .writedata
		output wire [3:0]  mem_4_s2_byteenable,                                //                                             .byteenable
		output wire        mem_4_s2_chipselect,                                //                                             .chipselect
		output wire        mem_4_s2_clken,                                     //                                             .clken
		input  wire        receive_packet_2_reset_reset_bridge_in_reset_reset, // receive_packet_2_reset_reset_bridge_in_reset.reset
		input  wire        tse_mac_rx_clock_connection_1_clk                   //                tse_mac_rx_clock_connection_1.clk
	);

	wire         receive_packet_2_avalon_master_translator_avalon_universal_master_0_waitrequest;   // mem_4_s2_translator:uav_waitrequest -> receive_packet_2_avalon_master_translator:uav_waitrequest
	wire  [31:0] receive_packet_2_avalon_master_translator_avalon_universal_master_0_readdata;      // mem_4_s2_translator:uav_readdata -> receive_packet_2_avalon_master_translator:uav_readdata
	wire         receive_packet_2_avalon_master_translator_avalon_universal_master_0_debugaccess;   // receive_packet_2_avalon_master_translator:uav_debugaccess -> mem_4_s2_translator:uav_debugaccess
	wire  [11:0] receive_packet_2_avalon_master_translator_avalon_universal_master_0_address;       // receive_packet_2_avalon_master_translator:uav_address -> mem_4_s2_translator:uav_address
	wire         receive_packet_2_avalon_master_translator_avalon_universal_master_0_read;          // receive_packet_2_avalon_master_translator:uav_read -> mem_4_s2_translator:uav_read
	wire   [3:0] receive_packet_2_avalon_master_translator_avalon_universal_master_0_byteenable;    // receive_packet_2_avalon_master_translator:uav_byteenable -> mem_4_s2_translator:uav_byteenable
	wire         receive_packet_2_avalon_master_translator_avalon_universal_master_0_readdatavalid; // mem_4_s2_translator:uav_readdatavalid -> receive_packet_2_avalon_master_translator:uav_readdatavalid
	wire         receive_packet_2_avalon_master_translator_avalon_universal_master_0_lock;          // receive_packet_2_avalon_master_translator:uav_lock -> mem_4_s2_translator:uav_lock
	wire         receive_packet_2_avalon_master_translator_avalon_universal_master_0_write;         // receive_packet_2_avalon_master_translator:uav_write -> mem_4_s2_translator:uav_write
	wire  [31:0] receive_packet_2_avalon_master_translator_avalon_universal_master_0_writedata;     // receive_packet_2_avalon_master_translator:uav_writedata -> mem_4_s2_translator:uav_writedata
	wire   [2:0] receive_packet_2_avalon_master_translator_avalon_universal_master_0_burstcount;    // receive_packet_2_avalon_master_translator:uav_burstcount -> mem_4_s2_translator:uav_burstcount

	system_design_altera_merlin_master_translator_191_g7h47bq #(
		.AV_ADDRESS_W                (10),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (12),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (0),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (1),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (0),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0),
		.SYNC_RESET                  (0),
		.WAITREQUEST_ALLOWANCE       (0)
	) receive_packet_2_avalon_master_translator (
		.clk                    (tse_mac_rx_clock_connection_1_clk),                                                 //   input,   width = 1,                       clk.clk
		.reset                  (receive_packet_2_reset_reset_bridge_in_reset_reset),                                //   input,   width = 1,                     reset.reset
		.uav_address            (receive_packet_2_avalon_master_translator_avalon_universal_master_0_address),       //  output,  width = 12, avalon_universal_master_0.address
		.uav_burstcount         (receive_packet_2_avalon_master_translator_avalon_universal_master_0_burstcount),    //  output,   width = 3,                          .burstcount
		.uav_read               (receive_packet_2_avalon_master_translator_avalon_universal_master_0_read),          //  output,   width = 1,                          .read
		.uav_write              (receive_packet_2_avalon_master_translator_avalon_universal_master_0_write),         //  output,   width = 1,                          .write
		.uav_waitrequest        (receive_packet_2_avalon_master_translator_avalon_universal_master_0_waitrequest),   //   input,   width = 1,                          .waitrequest
		.uav_readdatavalid      (receive_packet_2_avalon_master_translator_avalon_universal_master_0_readdatavalid), //   input,   width = 1,                          .readdatavalid
		.uav_byteenable         (receive_packet_2_avalon_master_translator_avalon_universal_master_0_byteenable),    //  output,   width = 4,                          .byteenable
		.uav_readdata           (receive_packet_2_avalon_master_translator_avalon_universal_master_0_readdata),      //   input,  width = 32,                          .readdata
		.uav_writedata          (receive_packet_2_avalon_master_translator_avalon_universal_master_0_writedata),     //  output,  width = 32,                          .writedata
		.uav_lock               (receive_packet_2_avalon_master_translator_avalon_universal_master_0_lock),          //  output,   width = 1,                          .lock
		.uav_debugaccess        (receive_packet_2_avalon_master_translator_avalon_universal_master_0_debugaccess),   //  output,   width = 1,                          .debugaccess
		.av_address             (receive_packet_2_avalon_master_address),                                            //   input,  width = 10,      avalon_anti_master_0.address
		.av_waitrequest         (receive_packet_2_avalon_master_waitrequest),                                        //  output,   width = 1,                          .waitrequest
		.av_byteenable          (receive_packet_2_avalon_master_byteenable),                                         //   input,   width = 4,                          .byteenable
		.av_chipselect          (receive_packet_2_avalon_master_chipselect),                                         //   input,   width = 1,                          .chipselect
		.av_readdata            (receive_packet_2_avalon_master_readdata),                                           //  output,  width = 32,                          .readdata
		.av_write               (receive_packet_2_avalon_master_write),                                              //   input,   width = 1,                          .write
		.av_writedata           (receive_packet_2_avalon_master_writedata),                                          //   input,  width = 32,                          .writedata
		.av_burstcount          (1'b1),                                                                              // (terminated),                                        
		.av_beginbursttransfer  (1'b0),                                                                              // (terminated),                                        
		.av_begintransfer       (1'b0),                                                                              // (terminated),                                        
		.av_read                (1'b0),                                                                              // (terminated),                                        
		.av_readdatavalid       (),                                                                                  // (terminated),                                        
		.av_lock                (1'b0),                                                                              // (terminated),                                        
		.av_debugaccess         (1'b0),                                                                              // (terminated),                                        
		.uav_clken              (),                                                                                  // (terminated),                                        
		.av_clken               (1'b1),                                                                              // (terminated),                                        
		.uav_response           (2'b00),                                                                             // (terminated),                                        
		.av_response            (),                                                                                  // (terminated),                                        
		.uav_writeresponsevalid (1'b0),                                                                              // (terminated),                                        
		.av_writeresponsevalid  ()                                                                                   // (terminated),                                        
	);

	system_design_altera_merlin_slave_translator_191_x56fcki #(
		.AV_ADDRESS_W                   (10),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (12),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0),
		.WAITREQUEST_ALLOWANCE          (0),
		.SYNC_RESET                     (0)
	) mem_4_s2_translator (
		.clk                    (tse_mac_rx_clock_connection_1_clk),                                                 //   input,   width = 1,                      clk.clk
		.reset                  (receive_packet_2_reset_reset_bridge_in_reset_reset),                                //   input,   width = 1,                    reset.reset
		.uav_address            (receive_packet_2_avalon_master_translator_avalon_universal_master_0_address),       //   input,  width = 12, avalon_universal_slave_0.address
		.uav_burstcount         (receive_packet_2_avalon_master_translator_avalon_universal_master_0_burstcount),    //   input,   width = 3,                         .burstcount
		.uav_read               (receive_packet_2_avalon_master_translator_avalon_universal_master_0_read),          //   input,   width = 1,                         .read
		.uav_write              (receive_packet_2_avalon_master_translator_avalon_universal_master_0_write),         //   input,   width = 1,                         .write
		.uav_waitrequest        (receive_packet_2_avalon_master_translator_avalon_universal_master_0_waitrequest),   //  output,   width = 1,                         .waitrequest
		.uav_readdatavalid      (receive_packet_2_avalon_master_translator_avalon_universal_master_0_readdatavalid), //  output,   width = 1,                         .readdatavalid
		.uav_byteenable         (receive_packet_2_avalon_master_translator_avalon_universal_master_0_byteenable),    //   input,   width = 4,                         .byteenable
		.uav_readdata           (receive_packet_2_avalon_master_translator_avalon_universal_master_0_readdata),      //  output,  width = 32,                         .readdata
		.uav_writedata          (receive_packet_2_avalon_master_translator_avalon_universal_master_0_writedata),     //   input,  width = 32,                         .writedata
		.uav_lock               (receive_packet_2_avalon_master_translator_avalon_universal_master_0_lock),          //   input,   width = 1,                         .lock
		.uav_debugaccess        (receive_packet_2_avalon_master_translator_avalon_universal_master_0_debugaccess),   //   input,   width = 1,                         .debugaccess
		.av_address             (mem_4_s2_address),                                                                  //  output,  width = 10,      avalon_anti_slave_0.address
		.av_write               (mem_4_s2_write),                                                                    //  output,   width = 1,                         .write
		.av_readdata            (mem_4_s2_readdata),                                                                 //   input,  width = 32,                         .readdata
		.av_writedata           (mem_4_s2_writedata),                                                                //  output,  width = 32,                         .writedata
		.av_byteenable          (mem_4_s2_byteenable),                                                               //  output,   width = 4,                         .byteenable
		.av_chipselect          (mem_4_s2_chipselect),                                                               //  output,   width = 1,                         .chipselect
		.av_clken               (mem_4_s2_clken),                                                                    //  output,   width = 1,                         .clken
		.av_read                (),                                                                                  // (terminated),                                       
		.av_begintransfer       (),                                                                                  // (terminated),                                       
		.av_beginbursttransfer  (),                                                                                  // (terminated),                                       
		.av_burstcount          (),                                                                                  // (terminated),                                       
		.av_readdatavalid       (1'b0),                                                                              // (terminated),                                       
		.av_waitrequest         (1'b0),                                                                              // (terminated),                                       
		.av_writebyteenable     (),                                                                                  // (terminated),                                       
		.av_lock                (),                                                                                  // (terminated),                                       
		.uav_clken              (1'b0),                                                                              // (terminated),                                       
		.av_debugaccess         (),                                                                                  // (terminated),                                       
		.av_outputenable        (),                                                                                  // (terminated),                                       
		.uav_response           (),                                                                                  // (terminated),                                       
		.av_response            (2'b00),                                                                             // (terminated),                                       
		.uav_writeresponsevalid (),                                                                                  // (terminated),                                       
		.av_writeresponsevalid  (1'b0)                                                                               // (terminated),                                       
	);

endmodule
